import {AuthProvider} from "@/app/(version3)/contexts/AuthContext";
import "./index.css"
import "./assets/css/style.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
         <script src="https://telegram.org/js/telegram-web-app.js"></script>
    </head>
    <body>
    <AuthProvider>
         {children}
    </AuthProvider>
      </body>
    </html>
  )
}
